# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-29 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.CharField(choices=[('male', '女生'), ('fmale', '男生')], max_length=12, verbose_name='性别')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
