# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-29 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '女生'), ('fmale', '男生')], max_length=12, null=True, verbose_name='性别'),
        ),
    ]
